/*
 * audioFX_config.h
 *
 *  Created on: Dec 14, 2017
 *      Author: Dean
 */

#ifndef AUDIOFX_AUDIOFX_CONFIG_H_
#define AUDIOFX_AUDIOFX_CONFIG_H_

#define AUDIO_BUFSIZE 128

#define AUDIO_SAMPLE_RATE 48000

#define AUDIO_TEMP_POOL_SIZE (256*sizeof(q31))

//DON'T CHANGE THESE!!
#define FM_LOOKUP_MUL 524288
#define FM_LOOKUP_INC 5401 //FM_INC (_F28(1./(AUDIO_SAMPLE_RATE+FM_CORRECTION)))
#define FM_LOOKUP_MASK 0x1FFFFFFF
#define FM_LOOKUP_MOD 0xFFFF
#define FM_MOD_MUL 0XA2F9836

#endif /* AUDIOFX_AUDIOFX_CONFIG_H_ */
