/*
 * audioFX_config.h
 *
 *  Created on: Dec 14, 2017
 *      Author: Dean
 */

#ifndef AUDIOFX_AUDIOFX_CONFIG_H_
#define AUDIOFX_AUDIOFX_CONFIG_H_

#define AUDIO_BUFSIZE 128

#define AUDIO_SAMPLE_RATE 48000

//DON'T CHANGE THESE!!
#define FM_LOOKUP_MUL 0X200000
#define FM_LOOKUP_INC 43252
#define FM_LOOKUP_MASK 0x1FFFFFFF
#define FM_LOOKUP_MOD 0x1FFFFF
#define FM_MOD_MUL 0XA2F9836

#endif /* AUDIOFX_AUDIOFX_CONFIG_H_ */
